let stri = 'Create String with Single Quote';
console.log(stri);

//string with constructor
let string = new String('Create String with String Constructor');
console.log(string);

//string with template literals
let strn = 'Template Litral String';
let newStr = `String created using ${strn}`;
console.log(newStr);

//multiline string
let str = `
    This is a
    multiline
    string`;

console.log(str);
